services:
  - type: web
    name: ping
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRY
        value: 7d
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: ARCJET_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: onboarding@resend.dev
      - key: EMAIL_FROM_NAME
        value: Ping
      - key: CLIENT_URL
        sync: false
